version: "3.7"
services:
  db_auth:
    container_name: db_auth
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USERS_DB_NAME: 'authentication'
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: ./dockerfiles/backend/Dockerfile
    ports: 
      - 8080:8080
    environment:
      HOSTNAME: localhost
      PORT: 8080
      POSTGRES_HOSTNAME: 'db_auth'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USERS_DB_NAME: 'users_db_name'
      POSTGRES_PRODUCTS_DB_NAME: 'products_db_products'
      POSTGRES_CARTS_DB_NAME: 'carts_db_carts'
      POSTGRES_ORDERS_DB_NAME: 'orders_db_orders'
      POSTGRES_REVIEWS_DB_NAME: 'reviews_db_reviews'
      POSTGRES_LOOTBOX_DB_NAME: 'lootbox_db_lootbox'
      POSTGRES_LOOTBOXINV_DB_NAME: 'lootboxinv_db_lootboxinv'
    links:
      - db_auth